export const countryNames: Record<string, string> = {
  AFG: 'Afghanistan',
  ALA: 'Åland Islands',
  ALB: 'Albania',
  DZA: 'Algeria',
  ASM: 'American Samoa',
  AND: 'Andorra',
  AGO: 'Angola',
  AIA: 'Anguilla',
  ATA: 'Antarctica',
  ATG: 'Antigua and Barbuda',
  ARG: 'Argentina',
  ARM: 'Armenia',
  ABW: 'Aruba',
  AUS: 'Australia',
  AUT: 'Austria',
  AZE: 'Azerbaijan',
  BHS: 'Bahamas',
  BHR: 'Bahrain',
  BGD: 'Bangladesh',
  BRB: 'Barbados',
  BLR: 'Belarus',
  BEL: 'Belgium',
  BLZ: 'Belize',
  BEN: 'Benin',
  BMU: 'Bermuda',
  BTN: 'Bhutan',
  BOL: 'Bolivia',
  BES: 'Bonaire, Sint Eustatius and Saba',
  BIH: 'Bosnia and Herzegovina',
  BWA: 'Botswana',
  BVT: 'Bouvet Island',
  BRA: 'Brazil',
  IOT: 'British Indian Ocean Territory',
  BRN: 'Brunei Darussalam',
  BGR: 'Bulgaria',
  BFA: 'Burkina Faso',
  BDI: 'Burundi',
  CPV: 'Cabo Verde',
  KHM: 'Cambodia',
  CMR: 'Cameroon',
  CAN: 'Canada',
  CYM: 'Cayman Islands',
  CAF: 'Central African Republic',
  TCD: 'Chad',
  CHL: 'Chile',
  CHN: 'China',
  CXR: 'Christmas Island',
  CCK: 'Cocos (Keeling) Islands',
  COL: 'Colombia',
  COM: 'Comoros',
  COG: 'Congo',
  COD: 'Congo (Democratic Republic of the)',
  COK: 'Cook Islands',
  CRI: 'Costa Rica',
  CIV: "Côte d'Ivoire",
  HRV: 'Croatia',
  CUB: 'Cuba',
  CUW: 'Curaçao',
  CYP: 'Cyprus',
  CZE: 'Czechia',
  DNK: 'Denmark',
  DJI: 'Djibouti',
  DMA: 'Dominica',
  DOM: 'Dominican Republic',
  ECU: 'Ecuador',
  EGY: 'Egypt',
  SLV: 'El Salvador',
  GNQ: 'Equatorial Guinea',
  ERI: 'Eritrea',
  EST: 'Estonia',
  SWZ: 'Eswatini',
  ETH: 'Ethiopia',
  FLK: 'Falkland Islands (Malvinas)',
  FRO: 'Faroe Islands',
  FJI: 'Fiji',
  FIN: 'Finland',
  FRA: 'France',
  GUF: 'French Guiana',
  PYF: 'French Polynesia',
  ATF: 'French Southern Territories',
  GAB: 'Gabon',
  GMB: 'Gambia',
  GEO: 'Georgia',
  DEU: 'Germany',
  GHA: 'Ghana',
  GIB: 'Gibraltar',
  GRC: 'Greece',
  GRL: 'Greenland',
  GRD: 'Grenada',
  GLP: 'Guadeloupe',
  GUM: 'Guam',
  GTM: 'Guatemala',
  GGY: 'Guernsey',
  GIN: 'Guinea',
  GNB: 'Guinea-Bissau',
  GUY: 'Guyana',
  HTI: 'Haiti',
  HMD: 'Heard Island and McDonald Islands',
  VAT: 'Holy See',
  HND: 'Honduras',
  HKG: 'Hong Kong',
  HUN: 'Hungary',
  ISL: 'Iceland',
  IND: 'India',
  IDN: 'Indonesia',
  IRN: 'Iran (Islamic Republic of)',
  IRQ: 'Iraq',
  IRL: 'Ireland',
  IMN: 'Isle of Man',
  ISR: 'Israel',
  ITA: 'Italy',
  JAM: 'Jamaica',
  JPN: 'Japan',
  JEY: 'Jersey',
  JOR: 'Jordan',
  KAZ: 'Kazakhstan',
  KEN: 'Kenya',
  KIR: 'Kiribati',
  PRK: "Korea (Democratic People's Republic of)",
  KOR: 'Korea (Republic of)',
  KWT: 'Kuwait',
  KGZ: 'Kyrgyzstan',
  LAO: "Lao People's Democratic Republic",
  LVA: 'Latvia',
  LBN: 'Lebanon',
  LSO: 'Lesotho',
  LBR: 'Liberia',
  LBY: 'Libya',
  LIE: 'Liechtenstein',
  LTU: 'Lithuania',
  LUX: 'Luxembourg',
  MAC: 'Macao',
  MDG: 'Madagascar',
  MWI: 'Malawi',
  MYS: 'Malaysia',
  MDV: 'Maldives',
  MLI: 'Mali',
  MLT: 'Malta',
  MHL: 'Marshall Islands',
  MTQ: 'Martinique',
  MRT: 'Mauritania',
  MUS: 'Mauritius',
  MYT: 'Mayotte',
  MEX: 'Mexico',
  FSM: 'Micronesia (Federated States of)',
  MDA: 'Moldova (Republic of)',
  MCO: 'Monaco',
  MNG: 'Mongolia',
  MNE: 'Montenegro',
  MSR: 'Montserrat',
  MAR: 'Morocco',
  MOZ: 'Mozambique',
  MMR: 'Myanmar',
  NAM: 'Namibia',
  NRU: 'Nauru',
  NPL: 'Nepal',
  NLD: 'Netherlands',
  NCL: 'New Caledonia',
  NZL: 'New Zealand',
  NIC: 'Nicaragua',
  NER: 'Niger',
  NGA: 'Nigeria',
  NIU: 'Niue',
  NFK: 'Norfolk Island',
  MNP: 'Northern Mariana Islands',
  NOR: 'Norway',
  OMN: 'Oman',
  PAK: 'Pakistan',
  PLW: 'Palau',
  PSE: 'Palestine, State of',
  PAN: 'Panama',
  PNG: 'Papua New Guinea',
  PRY: 'Paraguay',
  PER: 'Peru',
  PHL: 'Philippines',
  PCN: 'Pitcairn',
  POL: 'Poland',
  PRT: 'Portugal',
  PRI: 'Puerto Rico',
  QAT: 'Qatar',
  MKD: 'Republic of North Macedonia',
  ROU: 'Romania',
  RUS: 'Russian Federation',
  RWA: 'Rwanda',
  REU: 'Réunion',
  BLM: 'Saint Barthélemy',
  SHN: 'Saint Helena, Ascension and Tristan da Cunha',
  KNA: 'Saint Kitts and Nevis',
  LCA: 'Saint Lucia',
  MAF: 'Saint Martin (French part)',
  SPM: 'Saint Pierre and Miquelon',
  VCT: 'Saint Vincent and the Grenadines',
  WSM: 'Samoa',
  SMR: 'San Marino',
  STP: 'Sao Tome and Principe',
  SAU: 'Saudi Arabia',
  SEN: 'Senegal',
  SRB: 'Serbia',
  SYC: 'Seychelles',
  SLE: 'Sierra Leone',
  SGP: 'Singapore',
  SXM: 'Sint Maarten (Dutch part)',
  SVK: 'Slovakia',
  SVN: 'Slovenia',
  SLB: 'Solomon Islands',
  SOM: 'Somalia',
  ZAF: 'South Africa',
  SGS: 'South Georgia and the South Sandwich Islands',
  SSD: 'South Sudan',
  ESP: 'Spain',
  LKA: 'Sri Lanka',
  SDN: 'Sudan',
  SUR: 'Suriname',
  SJM: 'Svalbard and Jan Mayen',
  SWE: 'Sweden',
  CHE: 'Switzerland',
  SYR: 'Syrian Arab Republic',
  TWN: 'Taiwan, Province of China',
  TJK: 'Tajikistan',
  TZA: 'Tanzania, United Republic of',
  THA: 'Thailand',
  TLS: 'Timor-Leste',
  TGO: 'Togo',
  TKL: 'Tokelau',
  TON: 'Tonga',
  TTO: 'Trinidad and Tobago',
  TUN: 'Tunisia',
  TUR: 'Turkey',
  TKM: 'Turkmenistan',
  TCA: 'Turks and Caicos Islands',
  TUV: 'Tuvalu',
  UGA: 'Uganda',
  UKR: 'Ukraine',
  ARE: 'United Arab Emirates',
  GBR: 'United Kingdom',
  USA: 'United States of America',
  UMI: 'United States Minor Outlying Islands',
  URY: 'Uruguay',
  UZB: 'Uzbekistan',
  VUT: 'Vanuatu',
  VEN: 'Venezuela (Bolivarian Republic of)',
  VNM: 'Viet Nam',
  VGB: 'Virgin Islands (British)',
  VIR: 'Virgin Islands (U.S.)',
  WLF: 'Wallis and Futuna',
  ESH: 'Western Sahara',
  YEM: 'Yemen',
  ZMB: 'Zambia',
  ZWE: 'Zimbabwe'
}

// ... existing imports and code ...

// Mapping from ISO‑3 codes to ISO‑2 codes (all lowercase).
export const iso3Mapping: Record<string, string> = {
  AFG: 'af',
  ALA: 'ax',
  ALB: 'al',
  DZA: 'dz',
  ASM: 'as',
  AND: 'ad',
  AGO: 'ao',
  AIA: 'ai',
  ATA: 'aq',
  ATG: 'ag',
  ARG: 'ar',
  ARM: 'am',
  ABW: 'aw',
  AUS: 'au',
  AUT: 'at',
  AZE: 'az',
  BHS: 'bs',
  BHR: 'bh',
  BGD: 'bd',
  BRB: 'bb',
  BLR: 'by',
  BEL: 'be',
  BLZ: 'bz',
  BEN: 'bj',
  BMU: 'bm',
  BTN: 'bt',
  BOL: 'bo',
  BES: 'bq',
  BIH: 'ba',
  BWA: 'bw',
  BVT: 'bv',
  BRA: 'br',
  IOT: 'io',
  BRN: 'bn',
  BGR: 'bg',
  BFA: 'bf',
  BDI: 'bi',
  CPV: 'cv',
  KHM: 'kh',
  CMR: 'cm',
  CAN: 'ca',
  CYM: 'ky',
  CAF: 'cf',
  TCD: 'td',
  CHL: 'cl',
  CHN: 'cn',
  CXR: 'cx',
  CCK: 'cc',
  COL: 'co',
  COM: 'km',
  COG: 'cg',
  COD: 'cd',
  COK: 'ck',
  CRI: 'cr',
  CIV: 'ci',
  HRV: 'hr',
  CUB: 'cu',
  CUW: 'cw',
  CYP: 'cy',
  CZE: 'cz',
  DNK: 'dk',
  DJI: 'dj',
  DMA: 'dm',
  DOM: 'do',
  ECU: 'ec',
  EGY: 'eg',
  SLV: 'sv',
  GNQ: 'gq',
  ERI: 'er',
  EST: 'ee',
  SWZ: 'sz',
  ETH: 'et',
  FLK: 'fk',
  FRO: 'fo',
  FJI: 'fj',
  FIN: 'fi',
  FRA: 'fr',
  GUF: 'gf',
  PYF: 'pf',
  ATF: 'tf',
  GAB: 'ga',
  GMB: 'gm',
  GEO: 'ge',
  DEU: 'de',
  GHA: 'gh',
  GIB: 'gi',
  GRC: 'gr',
  GRL: 'gl',
  GRD: 'gd',
  GLP: 'gp',
  GUM: 'gu',
  GTM: 'gt',
  GGY: 'gg',
  GIN: 'gn',
  GNB: 'gw',
  GUY: 'gy',
  HTI: 'ht',
  HMD: 'hm',
  VAT: 'va',
  HND: 'hn',
  HKG: 'hk',
  HUN: 'hu',
  ISL: 'is',
  IND: 'in',
  IDN: 'id',
  IRN: 'ir',
  IRQ: 'iq',
  IRL: 'ie',
  IMN: 'im',
  ISR: 'il',
  ITA: 'it',
  JAM: 'jm',
  JPN: 'jp',
  JEY: 'je',
  JOR: 'jo',
  KAZ: 'kz',
  KEN: 'ke',
  KIR: 'ki',
  PRK: 'kp',
  KOR: 'kr',
  KWT: 'kw',
  KGZ: 'kg',
  LAO: 'la',
  LVA: 'lv',
  LBN: 'lb',
  LSO: 'ls',
  LBR: 'lr',
  LBY: 'ly',
  LIE: 'li',
  LTU: 'lt',
  LUX: 'lu',
  MAC: 'mo',
  MDG: 'mg',
  MWI: 'mw',
  MYS: 'my',
  MDV: 'mv',
  MLI: 'ml',
  MLT: 'mt',
  MHL: 'mh',
  MTQ: 'mq',
  MRT: 'mr',
  MUS: 'mu',
  MYT: 'yt',
  MEX: 'mx',
  FSM: 'fm',
  MDA: 'md',
  MCO: 'mc',
  MNG: 'mn',
  MNE: 'me',
  MSR: 'ms',
  MAR: 'ma',
  MOZ: 'mz',
  MMR: 'mm',
  NAM: 'na',
  NRU: 'nr',
  NPL: 'np',
  NLD: 'nl',
  NCL: 'nc',
  NZL: 'nz',
  NIC: 'ni',
  NER: 'ne',
  NGA: 'ng',
  NIU: 'nu',
  NFK: 'nf',
  MNP: 'mp',
  NOR: 'no',
  OMN: 'om',
  PAK: 'pk',
  PLW: 'pw',
  PSE: 'ps',
  PAN: 'pa',
  PNG: 'pg',
  PRY: 'py',
  PER: 'pe',
  PHL: 'ph',
  PCN: 'pn',
  POL: 'pl',
  PRT: 'pt',
  PRI: 'pr',
  QAT: 'qa',
  MKD: 'mk',
  ROU: 'ro',
  RUS: 'ru',
  RWA: 'rw',
  REU: 're',
  BLM: 'bl',
  SHN: 'sh',
  KNA: 'kn',
  LCA: 'lc',
  MAF: 'mf',
  SPM: 'pm',
  VCT: 'vc',
  WSM: 'ws',
  SMR: 'sm',
  STP: 'st',
  SAU: 'sa',
  SEN: 'sn',
  SRB: 'rs',
  SYC: 'sc',
  SLE: 'sl',
  SGP: 'sg',
  SXM: 'sx',
  SVK: 'sk',
  SVN: 'si',
  SLB: 'sb',
  SOM: 'so',
  ZAF: 'za',
  SGS: 'gs',
  SSD: 'ss',
  ESP: 'es',
  LKA: 'lk',
  SDN: 'sd',
  SUR: 'sr',
  SJM: 'sj',
  SWE: 'se',
  CHE: 'ch',
  SYR: 'sy',
  TWN: 'tw',
  TJK: 'tj',
  TZA: 'tz',
  THA: 'th',
  TLS: 'tl',
  TGO: 'tg',
  TKL: 'tk',
  TON: 'to',
  TTO: 'tt',
  TUN: 'tn',
  TUR: 'tr',
  TKM: 'tm',
  TCA: 'tc',
  TUV: 'tv',
  UGA: 'ug',
  UKR: 'ua',
  ARE: 'ae',
  GBR: 'gb',
  USA: 'us',
  UMI: 'um',
  URY: 'uy',
  UZB: 'uz',
  VUT: 'vu',
  VEN: 've',
  VNM: 'vn',
  VGB: 'vg',
  VIR: 'vi',
  WLF: 'wf',
  ESH: 'eh',
  YEM: 'ye',
  ZMB: 'zm',
  ZWE: 'zw'
}
